### ISSUE TITLE
Risk of Rain 2 Selector

### ISSUE THREAD

**Issue by Plutonarus** [risk-of-thunder/RoR2VersionSelector#3]
### What did you expect to happen?

Not sure if it's a bug or not...

I downloaded your RoR2Selector.exe to downpatch so I could avoid Gearbox shenanigans.

### Instead of that, what actually happened?

When I get to the window where I input username and password, it doesn't give me an option for the password and when I try with just the username, it tells me, \DepotDownloader.exe' is not recognized as an internal or external command, operable program or batch file."

The link I was given to watch this process is here:  https://www.youtube.com/watch?v=isxPWzuh97U&t=182s

![downpatch issue](https://github.com/user-attachments/assets/abac2369-1f22-410b-8313-6880a7e4defd)
 This screenshot is what happens when I try to download without inputting a password option that's not there.

### Which operating system are you running on?

Windows

### Version

Just signed up for it so the latest.

### Additional Information

I uninstalled the game a couple weeks ago to take a break and didn't have it installed when the SotS dlc was released.  
I use Thunderstore to play with mods.

**Comment by xiaoxiao921** [comment]
Should be fixed with the latest release, tell me if it still doesn't work
