### ISSUE TITLE
Passwords containing special characters break the Steam login script

### ISSUE THREAD

**Issue by Salty4life** [risk-of-thunder/RoR2VersionSelector#4]
### What did you expect to happen?

Was expected for the program to login and require me to authenticate via the steam mobile app

### Instead of that, what actually happened?

Program couldn't input all the password characters and would fail login

### Which operating system are you running on?

Windows

### Version

Latest

**Comment by xiaoxiao921** [comment]
Are you using the latest version? Password is now input inside the DepotDownloader console which is supposed to support special characters

**Comment by Salty4life** [comment]
Didn't realize it was updated, the issue is resolved.
My bad for not checking
