### ISSUE TITLE
RoR2VersionSelector closes after a certain time

### ISSUE THREAD

**Issue by DeadThor0** [risk-of-thunder/RoR2VersionSelector#5]
### What did you expect to happen?

i expected to put my log ins into the version selector 

### Instead of that, what actually happened?

but instead all the screens opened by the selector all close after about 15 seconds ( i stop watched).

### Which operating system are you running on?

Windows

### Version

1.2.4.4

**Comment by xiaoxiao921** [comment]
I can't replicate, if you can have a video of it happening this would be great
