### ISSUE TITLE
no exe?

### ISSUE THREAD

**Issue by bananabull** [risk-of-thunder/RoR2VersionSelector#6]
### What did you expect to happen?

to see an exe file to do the thing

### Instead of that, what actually happened?

only folder, cs files and resx files which i can't run or I'm just being dumb can't tell but i don't see an exe to run the thing

### Which operating system are you running on?

Windows

### Version

latest

**Comment by harbingerofme** [comment]
You've downloaded the source code. Head over to the [releases](https://github.com/risk-of-thunder/RoR2VersionSelector/releases) for downloads of the executable
