### ISSUE TITLE
Error copying folder devotion update.

### ISSUE THREAD

**Issue by Joaozinhodopineu2** [risk-of-thunder/RoR2VersionSelector#7]
### What did you expect to happen?

I expected the program to copy the files into my steam directory

### Instead of that, what actually happened?

It gave me an error
![image_2024-11-05_130453363](https://github.com/user-attachments/assets/a2826b10-01f0-4f13-bdca-f0e8f8ce7aaf)

### Which operating system are you running on?

Windows

### Version

The latest (I've downloaded it yesterday and today too)

### Relevant log output

```shell
I've tried multiple times, and it still happens. Might have something to do with the latest patch? Idk.
```

**Comment by xiaoxiao921** [comment]
Fixed in the latest version
